CREATE TABLE TIPO_EQUIPAMENTO(
ID SERIAL PRIMARY KEY,
DESCRICAO VARCHAR(255));

CREATE TABLE VEICULO(
ID SERIAL PRIMARY KEY,
INQUILINO_ID INTEGER,
TIPO VARCHAR(100),
PLACA VARCHAR(30),
NUMERO VARCHAR(50),
DESCRICAO VARCHAR(255),
SITUACAO VARCHAR(100),
INFORMACOES VARCHAR(500));


CREATE TABLE EQUIPAMENTO(
ID SERIAL PRIMARY KEY,
INQUILINO_ID INTEGER,
USUARIO_ID INTEGER,
VEICULO_ID INTEGER REFERENCES VEICULO,
TIPO VARCHAR(100),
NUMERO VARCHAR(50),
DESCRICAO VARCHAR(255),
SITUACAO VARCHAR(100),
INFORMACOES VARCHAR(500));

					
CREATE TABLE EVENTO(
ID SERIAL PRIMARY KEY,
INQUILINO_ID INTEGER,
EQUIPAMENTO_ID INTEGER REFERENCES EQUIPAMENTO,
TIPO VARCHAR(100),
DESCRICAO VARCHAR(255),
DATA_INICIO timestamptz,
DATA_FIM timestamptz,
SITUACAO VARCHAR(100),
INFORMACOES VARCHAR(500));					
					
					
					

